web/router.ex
defmodule FirstProject.Router do
  use FirstProject.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FirstProject do
    pipe_through :browser # Use the default browser stack
    get "/hello/:name", HelloController, :show
    get "/", PageController, :index
    get "/user", UserController, :index
    get "/show/:id", UserController, :show
    ##get "/Service", ServiceController, :index
    resources "/services", ServiceController

  end

  # Other scopes may use custom stacks.
  # scope "/api", FirstProject do
  #   pipe_through :api
  # end
end

lib/firstProject/endpoint.ex
defmodule FirstProject.Endpoint do
  use Phoenix.Endpoint, otp_app: :firstProject

  socket "/socket", FirstProject.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :firstProject, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_firstProject_key",
    signing_salt: "qOO//HcB"

  plug FirstProject.Router
end

lib/firstProject/repo.ex
defmodule FirstProject.Repo do
  use Ecto.Repo, otp_app: :firstProject

  @moduledoc """
In memory repository.
"""
  def allF(FirstProject.User) do
    [%FirstProject.User{id: "1",name: "Shibly", username: "shibly",password: "123456"},
  %FirstProject.User{id: "2",name: "Karim", username: "karim",password: "45678"},
%FirstProject.User{id: "3",name: "Rahim", username: "rahim",password: "4578"},
%FirstProject.User{id: "4",name: "Kashem", username: "kashem",password: "1234"}]
  end
  def allF(_module) do
     []
   end
  def getItem(module,id) do
    Enum.find allF(module),fn(map)->map.id==id
  end
end
  def getItem_by(module,param) do
    Enum.find allF(module),fn(map)->
      Enum.find?(param,fn{key,val}->Map.get(map,key)==val end)
    end
  end
end

web/models/content.ex
defmodule FirstProject.Content do
  use FirstProject.Web, :model
  schema "content" do
    field :name, :string
    field :details, :string
    field :contentId, :string, virtual: true
    field :authorized_by, :string
    timestamps
  end
end

web/models/customer.ex
defmodule FirstProject.Customer do
  use FirstProject.Web, :model
  schema "customer" do
    field :name, :string
    field :username, :string
    field :password , :string, virtual: true
    field :password_hash, :string
    timestamps
  end
end

web/models/service.ex
defmodule FirstProject.Service do
  use FirstProject.Web, :model

  schema "services" do
    field :body, :string
    field :user_id, :integer

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body, :user_id])
    |> validate_required([:body, :user_id])
  end
end

web/models/user.ex
defmodule FirstProject.User do
  defstruct [:id, :username, :name, :password]
end

web/controllers/hello_controller.ex
defmodule FirstProject.HelloController do
  use FirstProject.Web, :controller
  def show(conn, %{"name" => name}) do
    render conn, "world.html", name: name
  end
end

web/controllers/page_controller.ex
defmodule FirstProject.PageController do
  use FirstProject.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/service_controller.ex
defmodule FirstProject.ServiceController do
  use FirstProject.Web, :controller

  alias FirstProject.Service

  def index(conn, _params) do
    services = Repo.all(Service)
    render(conn, "index.html", services: services)
  end

  def new(conn, _params) do
    changeset = Service.changeset(%Service{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"service" => service_params}) do
    changeset = Service.changeset(%Service{}, service_params)

    case Repo.insert(changeset) do
      {:ok, _service} ->
        conn
        |> put_flash(:info, "Service created successfully.")
        |> redirect(to: service_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    service = Repo.get!(Service, id)
    render(conn, "show.html", service: service)
  end

  def edit(conn, %{"id" => id}) do
    service = Repo.get!(Service, id)
    changeset = Service.changeset(service)
    render(conn, "edit.html", service: service, changeset: changeset)
  end

  def update(conn, %{"id" => id, "service" => service_params}) do
    service = Repo.get!(Service, id)
    changeset = Service.changeset(service, service_params)

    case Repo.update(changeset) do
      {:ok, service} ->
        conn
        |> put_flash(:info, "Service updated successfully.")
        |> redirect(to: service_path(conn, :show, service))
      {:error, changeset} ->
        render(conn, "edit.html", service: service, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    service = Repo.get!(Service, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(service)

    conn
    |> put_flash(:info, "Service deleted successfully.")
    |> redirect(to: service_path(conn, :index))
  end
end

web/controllers/user_controller.ex
defmodule FirstProject.UserController do
      use FirstProject.Web, :controller
      def index(conn, _params) do
        users=Repo.allF(FirstProject.User)
        render conn, "index.html", users: users
      end
      def show(conn,%{"id" => id}) do
        user = Repo.getItem(FirstProject.User,id)
        render conn, "show.html", user: user
      end
end

web/views/error_view.ex
defmodule FirstProject.ErrorView do
  use FirstProject.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/hello_view.ex
defmodule FirstProject.HelloView do
   use FirstProject.Web, :view
 end

web/views/layout_view.ex
defmodule FirstProject.LayoutView do
  use FirstProject.Web, :view
  def title do
    "Awesome New Title!"
  end
end

web/views/page_view.ex
defmodule FirstProject.PageView do
  use FirstProject.Web, :view
end

web/views/service_view.ex
defmodule FirstProject.ServiceView do
  use FirstProject.Web, :view
end

web/views/user_view.ex
defmodule FirstProject.UserView do
  use FirstProject.Web, :view
  alias FirstProject.User
  def first_name( %User{name: name} ) do
  name
  |> String.split(" ")
  |> Enum.at(0)
  end
  def selectListGenerate(%User{name: name, id: id}) do
    item={name,id}
  end
  def itemGet(users) do
    item = for i <- users do
     IO.inspect selectListGenerate(i)
     end
     #item=from(p in users, select: {p.id, p.name})
    IO.inspect item

  end

end

web/templates/hello/world.html.eex
<h2>Show service</h2>

<h1>Hellow world ! Here we go <%= String.capitalize @name  %> </h1>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello FirstProject!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/service/edit.html.eex
<h2>Edit service</h2>

<%= render "form.html", changeset: @changeset,
                        action: service_path(@conn, :update, @service) %>

<%= link "Back", to: service_path(@conn, :index) %>

web/templates/service/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= label f, :user_id, class: "control-label" %>
    <%= number_input f, :user_id, class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/service/index.html.eex
<h2>Listing services</h2>

<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for service <- @services do %>
    <tr>
      <td><%= service.body %></td>
      <td><%= service.user_id %></td>

      <td class="text-right">
        <%= link "Show", to: service_path(@conn, :show, service), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: service_path(@conn, :edit, service), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: service_path(@conn, :delete, service), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New service", to: service_path(@conn, :new) %>

web/templates/service/new.html.eex
<h2>New service</h2>

<%= render "form.html", changeset: @changeset,
                        action: service_path(@conn, :create) %>

<%= link "Back", to: service_path(@conn, :index) %>

web/templates/service/show.html.eex
<h2>Show service</h2>

<ul>

  <li>
    <strong>Body:</strong>
    <%= @service.body %>
  </li>

  <li>
    <strong>User:</strong>
    <%= @service.user_id %>
  </li>

</ul>

<%= link "Edit", to: service_path(@conn, :edit, @service) %>
<%= link "Back", to: service_path(@conn, :index) %>

web/templates/user/index.html.eex
<h1> Watch User</h1>
  <table class="table table-bordered table-responsive">
    <tr>
  <th>
    Name
  </th>
  <th>
    Action
  </th>
    </tr>
  <%= for user <- @users do %>
  <tr>
  <td><b><%= first_name(user) %></b> (<%= user.id %>)</td>
   <td><%= link "View", to: user_path(@conn, :show, user.id) %></td>
  </tr>
  <%= end %>
  </table>
  <form class="" action="index.html" method="post">
  <%= #select form, :name, itemGet(@users), class: "form-control"
  select(nil, :id, itemGet(@users),  prompt: "Choose your Name", class: "form-control" )
  %>
  </form>

web/templates/user/show.html.eex
<h1>
User Name
</h1>

<b><%= first_name(@user)%></b> <b><%= @user.id%></b>